// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC17qay2Sryf-Dl15QxSkRYVNO0yH-tQGA',
    appId: '1:169350874699:web:67fd0ca2adc028c11cafce',
    messagingSenderId: '169350874699',
    projectId: 'q-play-3ce7f',
    authDomain: 'q-play-3ce7f.firebaseapp.com',
    storageBucket: 'q-play-3ce7f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_M0Q3DBWbCkEqmw7cYLbEtmEgOXyoas8',
    appId: '1:169350874699:android:75e7df009d77aea51cafce',
    messagingSenderId: '169350874699',
    projectId: 'q-play-3ce7f',
    storageBucket: 'q-play-3ce7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl7arXNJhnsrQ1GeDvmT8opelsuEeHOPU',
    appId: '1:169350874699:ios:7ef7c3be1c17a5451cafce',
    messagingSenderId: '169350874699',
    projectId: 'q-play-3ce7f',
    storageBucket: 'q-play-3ce7f.firebasestorage.app',
    iosBundleId: 'com.qplay.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl7arXNJhnsrQ1GeDvmT8opelsuEeHOPU',
    appId: '1:169350874699:ios:7ef7c3be1c17a5451cafce',
    messagingSenderId: '169350874699',
    projectId: 'q-play-3ce7f',
    storageBucket: 'q-play-3ce7f.firebasestorage.app',
    iosBundleId: 'com.qplay.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC17qay2Sryf-Dl15QxSkRYVNO0yH-tQGA',
    appId: '1:169350874699:web:7359522bdc5f7e3a1cafce',
    messagingSenderId: '169350874699',
    projectId: 'q-play-3ce7f',
    authDomain: 'q-play-3ce7f.firebaseapp.com',
    storageBucket: 'q-play-3ce7f.firebasestorage.app',
  );
}
