import 'package:get/get.dart';


class Translate extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
    "ar": {
      "Choose your Language": "اختر لغتك",
      "Select the language you prefer to use in the app": "حدد اللغة التي تفضل استخدامها في التطبيق",

      "Welcome Back!": "مرحبًا بعودتك!",
      "Login to continue": "تسجيل الدخول للاستمرار",
      "Email Address": "البريد الإلكتروني",
      "Enter email": "أدخل البريد الإلكتروني",
      "Wrong email": "بريد إلكتروني غير صحيح",
      "Password": "كلمة المرور",
      "Enter password": "أدخل كلمة المرور",
      "Password must be at least 6 characters": "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
      "Forget password ?": "نسيت كلمة المرور ؟",
      "Login": "تسجيل الدخول",
      "OR": "أو",
      "Sign in with Google": "تسجيل الدخول باستخدام جوجل",
      "Continue as Guest": "إستمر كضيف",
      "Don't have an account? ": "ليس لديك حساب؟ ",
      "Sign Up": "إنشاء حساب",
      "Wrong email or password": "البريد الإلكتروني أو كلمة المرور خاطئة",

      "Create Account": "إنشاء حساب",
      "Sign up to get started": "قم بالتسجيل للبدء",
      "First Name": "الاسم الأول",
      "Last Name": "الاسم الأخير",
      "Enter first name": "أدخل الاسم الأول",
      "Enter last name": "أدخل الاسم الأخير",
      "Username": "اسم المستخدم",
      "Enter username": "أدخل اسم المستخدم",
      "Username must be at least 6 characters": "يجب أن يكون اسم المستخدم 6 أحرف على الأقل",
      "Invalid username. Use letters, numbers, underscores, or periods": "اسم المستخدم غير صالح. استخدم الأحرف أو الأرقام أو الشرطة السفلية أو النقاط",
      "Birthday": "تاريخ الميلاد",
      "Phone Number": "رقم الهاتف",
      "Wrong phone number": "رقم الهاتف خاطئ",
      "Search country": "بحث عن البلد",
      "Already have an account? ": "هل لديك حساب؟ ",
      "Sign In": "تسجيل الدخول",

      "Enter your email and we will send you an OTP to reset your password": "أدخل بريدك الإلكتروني وسنرسل لك رمز OTP لإعادة تعيين كلمة المرور الخاصة بك",
      "Send OTP": "إرسال الرمز",
      "Remember your password? ": "تذكرت كلمة المرور؟ ",
      "The OTP has been sent": "تم إرسال OTP",
      "resend": "إعادة الإرسال",
      "Resend the OTP in ": "إعادة إرسال OTP في ",
      "s": "ث",
      "Verify": "تحقق",
      "Invalid OTP": "رمز التحقق خاطئ",
      "Email not found": "لم يتم العثور على البريد الإلكتروني",
      'Phone number already registered' : 'رقم الهاتف مسجل بالفعل',
      'Email  already registered' : 'البريد الإلكتروني مسجل بالفعل',

      "New password": "كلمة المرور الجديدة",
      "Confirm password": "تأكيد كلمة المرور",
      "Passwords do not match": "كلمات المرور غير متطابقة",
      "Reset": "إعادة ضبط",
      "Password changed successfully": "تم تغيير كلمة المرور بنجاح",

      "Home": "الرئسية",
      "Notifications": "الإشعارات",
      "Profile": "الملف الشخصي",

      "No matches at the moment": "لا توجد مباريات في الوقت الحالي",

      "No Notifications Yet": "لا يوجد إشعارات حتى الآن",
      "When you get notifications, they’ll show up here": "عندما تتلقى إشعارات، ستظهر هنا",

      "Edit Profile": "تعديل الملف الشخصي",
      "Language": "اللغة",
      "Dark Mode": "الوضع المظلم",
      "Privacy Policy": "سياسة الخصوصية",
      "Help Center": "مركز المساعدة",
      "Logout": "تسجيل الخروج",
      "Are you sure you want to logout ?": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
      "Confirm": "تأكيد",
      "Cancel": "إلغاء",

      "Save": "حفظ",

      "Please sign in to continue": "يرجى تسجيل الدخول للمتابعة",

      "Error": "خطأ",
      "Warning": "تحذير",
      "Success": "نجاح",
      "Close": "إغلاق",
      "Yes": "نعم",
      "Are you sure ?": "هل أنت متأكد ؟",
      "Check your connectivity": "تحقق من إتصالك",
      "An error occurred, please try again later": "لقد حدث خطأ، أعد المحاولة لاحقا",
      "Current password": "كلمة المرور الحالية",
      "Current password is incorrect": "كلمة المرور الحالية غير صحيحة",
      "Update": "تحديث",
      "Change Password": "تغيير كلمة المرور",
      "Profile updated successfully": "تم تحديث الملف الشخصي بنجاح",


      "All": "الكل",
      "Football": "كرة القدم",
      "Padel": "بادل" ,

      "QAR": "ر.ق",
      "View Details": "عرض التفاصيل",
      "Missing": "متبقي",
      "Full Team": "الفريق مكتمل",
      "Match Details": "تفاصيل المباراة",
      "Match Information": "معلومات المباراة",
      "Sport Type": "نوع الرياضة",
      "Match Date": "تاريخ المباراة",
      "Price": "السعر",
      "Location Details": "تفاصيل الموقع",
      "Stadium Name": "اسم الملعب",
      "See Location on Map": "عرض الموقع على الخريطة",
      "Teams": "الفرق",
      "Description": "الوصف",

      "Status": "الحالة",
      "pending": "قيد الانتظار",
      "finished": "منتهي",

      "Missing Players": "اللاعبون المتبقون",

      "Red": "الأحمر",
      "Blue": "الأزرق",
      "Join": "إنضمام",

      "The Match has been deleted or cancelled": "تم حذف المباراة أو إلغاؤها",
      "This app is for testing purposes only": "هذا التطبيق لغرض الاختبار فقط",

      "UPCOMING": "مُقبل",
      "FINISHED": "منتهي",
      "per person": "للشخص الواحد",
      "Players": "اللاعبون",
      "Type": "النوع",
      "Date & Time": "التاريخ والوقت",
      "Match Type": "نوع المباراة",
      "Location": "الموقع",
      "View on Map": "عرض على الخريطة",
      "Available Services": "الخدمات المتاحة",
      "Goalkeeper": "حارس المرمى",
      "Referee": "الحكم",
      "Venue Features": "مميزات الملعب",
      "Join Match": "إنضمام للمباراة",
      "Already Enrolled": "مُسجل بالفعل",
      "Match Not Found": "المباراة غير موجودة",
      "The match has been deleted or cancelled": "تم حذف المباراة أو إلغاؤها",
      "Go Back": "العودة",

      'Previous payment used to join the team' : 'تم استخدام الدفعة السابقة للانضمام إلى الفريق',
      'Team is full' : 'الفريق مكتمل',
      'Mark all as read' : 'تعيين الكل كمقروء',

      'Payments' : 'المدفوعات',

      'NEW' : 'جديد',
      'PENDING' : 'قيد الانتظار',
      'PAID' : 'مدفوع',
      'CANCELED' : 'ملغى',
      'FAILED' : 'فشل',
      'REJECTED' : 'مرفوض',
      'REFUNDED' : 'مسترجع',
      'PENDING-REFUND' : 'في انتظار الاسترجاع',
      'REFUND-FAILED' : 'فشل الاسترجاع',
      'CREDIT' : 'رصيد',


      'Payment ID' : 'معرّف الدفع',
      'Transaction ID' : 'معرّف العملية',
      'Created At' : 'تاريخ الإنشاء',
      'Match' : 'المباراة',
      'Team' : 'الفريق',
      'Related Information' : 'معلومات ذات صلة',

      'ID' : 'المعرف',
      'Payment Details' : 'تفاصيل الدفع',
      'Payment Information' : 'معلومات الدفع',
      'Amount' : 'المبلغ',
      'Transaction Details' : 'تفاصيل المعاملة',
      'Last Updated' : 'آخر تحديث',
      'Related Match' : 'المباراة المرتبطة',
      'Related Team' : 'الفريق المرتبط',

      "Copied": "تم النسخ",
      "Payment ID copied to clipboard": "تم نسخ معرف الدفع إلى الحافظة",
      "Nothing to copy": "لا يوجد ما يتم نسخه",
      'Payment Not Found' : 'لم يتم العثور على الدفع',
      'The payment has been deleted or does not exist' : 'تم حذف عملية الدفع أو أنها غير موجودة',

      'No Payments Found' : 'لم يتم العثور على مدفوعات',
      'You haven\'t made any payments yet' : 'لم تقم بأي مدفوعات بعد',

      'Spots Available' : 'أماكن متاحة',
      'Team Full' : 'الفريق مكتمل',
      'Select Team' : 'اختر الفريق',
      'Choose which team you want to join' : 'اختر الفريق الذي تريد الانضمام إليه',

      'Authentication Required' : 'المصادقة مطلوبة',
      'Please log in to continue' : 'يرجى تسجيل الدخول للمتابعة',

      'No match found' : 'لم يتم العثور على المباراة',
      'This team is already full' : 'هذا الفريق مكتمل',
      'You already joined a team in this match' : 'لقد انضممت بالفعل إلى فريق في هذه المباراة',
      'Insufficient wallet balance' : 'رصيد المحفظة غير كافٍ',
      'Joined match successfully' : 'انضمت إلى المباراة بنجاح',
      'My Wallet' : 'محفظتي',
      'Wallet' : 'المحفظة',
      'No wallet found' : 'لم يتم العثور على المحفظة',
      'Q-Play' : 'كيو بلاي',
      'WALLET' : 'المحفظة',
      'Current Balance' : 'الرصيد الحالي',
      'transactions' : 'المعاملات',
      'Add Balance' : 'إضافة الرصيد',
      'Recent Activity' : 'النشاط الأخير',
      'See All' : 'مشاهدة الكل',
      'No transactions yet' : "لا توجد معاملات حتى الآن",
      'Balance Added' : "تمت إضافة الرصيد",
      'Payment' : 'دفع',
      'Today' : 'اليوم',
      'Yesterday' : 'أمس',
      'days ago' : 'منذ أيام',
      "Monday": "الإثنين",
      "Tuesday": "الثلاثاء",
      "Wednesday": "الأربعاء",
      "Thursday": "الخميس",
      "Friday": "الجمعة",
      "Saturday": "السبت",
      "Sunday": "الأحد",
      'Quick Select' : 'الاختيار السريع',
      'Amount must be a number greater than 1' : 'يجب أن يكون المبلغ عددًا أكبر من 1',
      'Transactions' : 'المعاملات',
      'Error Loading Wallet' : 'خطأ في تحميل المحفظة',
      'Unable to load wallet data. Please try again.' : 'تعذر تحميل بيانات المحفظة. يُرجى المحاولة مرة أخرى.',
      'Retry' : 'إعادة المحاولة',
      'No Transactions Found' : "لم يتم العثور على أي معاملات",
      'You haven\'t made any transactions yet' : "لم تقم بأي معاملات بعد",
      'Back to Wallet'  : 'العودة إلى المحفظة',
      'Total Transactions' : "إجمالي المعاملات",
      'Balance' : 'الرصيد',
      'Wallet ID' : 'معرف المحفظة',
      'INCOME' : 'دخل',
      'EXPENSE' : 'مصروف',
      'Transaction ID copied to clipboard' : 'تم نسخ معرف المعاملة إلى الحافظة',
      'Transaction Information' : 'معلومات المعاملة',
      'Date' : 'تاريخ',
      'User ID' : 'معرف المستخدم',
      'Transaction Not Found' : 'لم يتم العثور على المعاملة',
      'The transaction has been deleted or does not exist' : 'تم حذف المعاملة أو أنها غير موجودة',
      'Wallet Information' : 'معلومات المحفظة',

      'Account created successfully' : 'تم إنشاء الحساب بنجاح',

      'Due to violation of the terms of service, Farya has banned your account' : 'بسبب انتهاك شروط الخدمة، قامت Farya بحظر حسابك',
      'Is there an error ?\ncontact us' : 'هل يوجد خطأ ؟\nإتصل بنا',

      'Send Balance' : 'إرسال الرصيد'
    }
  };

}

//•